In [112]:
import pandas as pd #🐼

**iloc[]** (from 🐼) used for slicing dataframes.

In [113]:
data = pd.read_csv('amazon_fires_.csv')
data.head(4)

    ano      mes estado   numero  encontro
0  1998  Janeiro   Acre  0 Fires  1/1/1998
1  1999  Janeiro   Acre  0 Fires  1/1/1999
2  2000  Janeiro   Acre  0 Fires  1/1/2000
3  2001  Janeiro   Acre  0 Fires  1/1/2001

In [114]:
# 1. get the 1st to 9th row of ano column
data.iloc[0:10, 0]

0    1998
1    1999
2    2000
3    2001
4    2002
5    2003
6    2004
7    2005
8    2006
9    2007
Name: ano, dtype: int64

In [115]:
# 2. get 2nd to 22nd row of mes, estado, numero, encontro
data.iloc[1:22, 1:]

          mes estado    numero  encontro
1     Janeiro   Acre   0 Fires  1/1/1999
2     Janeiro   Acre   0 Fires  1/1/2000
3     Janeiro   Acre   0 Fires  1/1/2001
4     Janeiro   Acre   0 Fires  1/1/2002
5     Janeiro   Acre  10 Fires  1/1/2003
6     Janeiro   Acre   0 Fires  1/1/2004
7     Janeiro   Acre  12 Fires  1/1/2005
8     Janeiro   Acre   4 Fires  1/1/2006
9     Janeiro   Acre   0 Fires  1/1/2007
10    Janeiro   Acre   0 Fires  1/1/2008
11    Janeiro   Acre   0 Fires  1/1/2009
12    Janeiro   Acre   1 Fires  1/1/2010
13    Janeiro   Acre   0 Fires  1/1/2011
14    Janeiro   Acre   0 Fires  1/1/2012
15    Janeiro   Acre   0 Fires  1/1/2013
16    Janeiro   Acre   0 Fires  1/1/2014
17    Janeiro   Acre   1 Fires  1/1/2015
18    Janeiro   Acre  12 Fires  1/1/2016
19    Janeiro   Acre   0 Fires  1/1/2017
20  Fevereiro   Acre   0 Fires  1/1/1998
21  Fevereiro   Acre   0 Fires  1/1/1999

**value_counts()** (from 🐼) <br>
**value_counts()** : counts the number of occurences of a particular value in the column.<br>

In [116]:
data['mes'].value_counts()

mes
Janeiro      541
Fevereiro    540
Março        540
Abril        540
Maio         540
Junho        540
Julho        540
Agosto       540
Setembro     540
Outubro      540
Novembro     540
Dezembro     513
Name: count, dtype: int64

**DATA CLEANING FOR HR DATASET**

In [117]:
# Step 0: Import the dataset
df = pd.read_csv('hr_data.csv')
df.head(2)

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium

In [118]:
# Step 1: Renaming the columns
df.rename(columns={
    'employee_id' : 'eid',
    'number_project' : 'no._of_projects',
    'average_montly_hours' : 'avg_mon_hours',
    'time_spend_company' : 'time_spent_cpy',
    'Work_accident' : 'work_accident',
    'left' : 'left_company',
    'promotion_last_5years' : 'promo_last_5yrs',
    'department' : 'dept',
    'salary' : 'sal'
}, inplace=True)
df.head(2)

,eid,no._of_projects,avg_mon_hours,time_spent_cpy,work_accident,left_company,promo_last_5yrs,dept,sal
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium

In [119]:
# Step 2: Rearranging the columns
new_order = [0, 7, 1, 2, 3, 6, 8, 4, 5]
df[df.columns[new_order]].head(2)

,eid,dept,no._of_projects,avg_mon_hours,time_spent_cpy,promo_last_5yrs,sal,work_accident,left_company
0,1003,sales,2,157,3,0,low,0,1
1,1005,sales,5,262,6,0,medium,0,1

In [120]:
# Step 3: Updating the values in the columns
df['dept'].unique()

dict_var = {
    'sales' : 'Sales D',
    'accounting' : 'Accounts D',
    'hr' : 'HR D',
    'technical' : 'Tech D',
    'support' : 'TechSupport D',
    'management' : 'Mgmt D',
    'IT' : 'IT D',
    'product_mng' : 'ProMgmt D',
    'marketing' : 'Market D',
    'RandD' : 'RandD D'
}
df['dept'] = df['dept'].map(dict_var)
df.head(80)

,eid,no._of_projects,avg_mon_hours,time_spent_cpy,work_accident,left_company,promo_last_5yrs,dept,sal
0,1003,2,157,3,0,1,0,Sales D,low
1,1005,5,262,6,0,1,0,Sales D,medium
2,1486,7,272,4,0,1,0,Sales D,medium
3,1038,5,223,5,0,1,0,Sales D,low
4,1057,2,159,3,0,1,0,Sales D,low
...,...,...,...,...,...,...,...,...,...
75,1466,7,306,4,0,1,0,ProMgmt D,medium
76,1467,6,295,4,0,1,0,ProMgmt D,medium
77,1473,2,137,3,0,1,0,Market D,medium
78,13107,2,157,3,0,1,0,Sales D,low
79,1489,2,142,3,0,1,0,Accounts D,low

In [121]:
# Step 4: Removing unwanted data from the column
df['dept'] = df['dept'].str.strip(' D')
df

,eid,no._of_projects,avg_mon_hours,time_spent_cpy,work_accident,left_company,promo_last_5yrs,dept,sal
0,1003,2,157,3,0,1,0,Sales,low
1,1005,5,262,6,0,1,0,Sales,medium
2,1486,7,272,4,0,1,0,Sales,medium
3,1038,5,223,5,0,1,0,Sales,low
4,1057,2,159,3,0,1,0,Sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,TechSupport,low
14995,87673,2,160,3,0,1,0,TechSupport,low
14996,87679,2,143,3,0,1,0,TechSupport,low
14997,87681,6,280,4,0,1,0,TechSupport,low
14998,87684,2,158,3,0,1,0,TechSupport,low

In [122]:
# 5. Changing the datatype of the column
# display(df.info())
df['avg_mon_hours'] = df['avg_mon_hours'].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   eid              14999 non-null  int64
 1   no._of_projects  14999 non-null  int64
 2   avg_mon_hours    14999 non-null  float64
 3   time_spent_cpy   14999 non-null  int64
 4   work_accident    14999 non-null  int64
 5   left_company     14999 non-null  int64
 6   promo_last_5yrs  14999 non-null  int64
 7   dept             14999 non-null  object
 8   sal              14999 non-null  object
dtypes: float64(1), int64(6), object(2)
memory usage: 1.0+ MB

In [123]:
# 6. Changing particular value in column
df['dept'] = df['dept'].str.replace('TechSupport', 'Support')
df.tail(3)

,eid,no._of_projects,avg_mon_hours,time_spent_cpy,work_accident,left_company,promo_last_5yrs,dept,sal
14996,87679,2,143.0,3,0,1,0,Support,low
14997,87681,6,280.0,4,0,1,0,Support,low
14998,87684,2,158.0,3,0,1,0,Support,low

In [124]:
# 7. Applying in-built functions on column
df['sal'] = df['sal'].str.upper()
df.head(3)

,eid,no._of_projects,avg_mon_hours,time_spent_cpy,work_accident,left_company,promo_last_5yrs,dept,sal
0,1003,2,157.0,3,0,1,0,Sales,LOW
1,1005,5,262.0,6,0,1,0,Sales,MEDIUM
2,1486,7,272.0,4,0,1,0,Sales,MEDIUM

In [125]:
# 8. Handling missing values
# i) dropping NaN values
# ii) replacing NaN values with 0 or avg
# iii) forward filling or back filling
# iv) dropping duplicates
df.dropna()
df.fillna(0)
df.fillna('ffill')
df.fillna('bfill')
df.drop_duplicates(inplace = True)
df

,eid,no._of_projects,avg_mon_hours,time_spent_cpy,work_accident,left_company,promo_last_5yrs,dept,sal
0,1003,2,157.0,3,0,1,0,Sales,LOW
1,1005,5,262.0,6,0,1,0,Sales,MEDIUM
2,1486,7,272.0,4,0,1,0,Sales,MEDIUM
3,1038,5,223.0,5,0,1,0,Sales,LOW
4,1057,2,159.0,3,0,1,0,Sales,LOW
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151.0,3,0,1,0,Support,LOW
14995,87673,2,160.0,3,0,1,0,Support,LOW
14996,87679,2,143.0,3,0,1,0,Support,LOW
14997,87681,6,280.0,4,0,1,0,Support,LOW
14998,87684,2,158.0,3,0,1,0,Support,LOW

In [126]:
# 9. Removing unwanted column from the dataframe
df.drop('dept', axis=1)
df.head(3)

,eid,no._of_projects,avg_mon_hours,time_spent_cpy,work_accident,left_company,promo_last_5yrs,dept,sal
0,1003,2,157.0,3,0,1,0,Sales,LOW
1,1005,5,262.0,6,0,1,0,Sales,MEDIUM
2,1486,7,272.0,4,0,1,0,Sales,MEDIUM

In [127]:
# 10. Removing unwanted rows
df.drop(1, axis=0, inplace=True)
df.head(3)

,eid,no._of_projects,avg_mon_hours,time_spent_cpy,work_accident,left_company,promo_last_5yrs,dept,sal
0,1003,2,157.0,3,0,1,0,Sales,LOW
2,1486,7,272.0,4,0,1,0,Sales,MEDIUM
3,1038,5,223.0,5,0,1,0,Sales,LOW

In [128]:
# 11. Resetting index
df.reset_index() # resets the index and displays old index in 'index' column in the dataframe
df.head()

,eid,no._of_projects,avg_mon_hours,time_spent_cpy,work_accident,left_company,promo_last_5yrs,dept,sal
0,1003,2,157.0,3,0,1,0,Sales,LOW
2,1486,7,272.0,4,0,1,0,Sales,MEDIUM
3,1038,5,223.0,5,0,1,0,Sales,LOW
4,1057,2,159.0,3,0,1,0,Sales,LOW
5,1060,2,153.0,3,0,1,0,Sales,LOW

In [129]:
# 12. Setting column name as index
df.set_index('eid')

,no._of_projects,avg_mon_hours,time_spent_cpy,work_accident,left_company,promo_last_5yrs,dept,sal
eid,,,,,,,,
1003,2,157.0,3,0,1,0,Sales,LOW
1486,7,272.0,4,0,1,0,Sales,MEDIUM
1038,5,223.0,5,0,1,0,Sales,LOW
1057,2,159.0,3,0,1,0,Sales,LOW
1060,2,153.0,3,0,1,0,Sales,LOW
...,...,...,...,...,...,...,...,...
87670,2,151.0,3,0,1,0,Support,LOW
87673,2,160.0,3,0,1,0,Support,LOW
87679,2,143.0,3,0,1,0,Support,LOW
87681,6,280.0,4,0,1,0,Support,LOW
87684,2,158.0,3,0,1,0,Support,LOW