In [2]:
# importing necessary libraries
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error

In [19]:
# load the data
df = pd.read_csv('House_price_prediction.csv')
df.head()

,Unnamed: 0,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
0,1,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,1.0,202.0,160.2564,1480000.0
1,2,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,0.0,156.0,79.0000,1035000.0
2,4,Abbotsford,3,h,SP,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,0.0,134.0,150.0000,1465000.0
3,5,Abbotsford,3,h,PI,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,1.0,94.0,160.2564,850000.0
4,6,Abbotsford,4,h,VB,Nelson,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,1.0,2.0,120.0,142.0000,1600000.0

In [20]:
# dropping first column (Unnamed: 0)
df = df.drop('Unnamed: 0', axis=1) # axis=0 for row, axis=1 for column
df.head()

,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
0,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,1.0,202.0,160.2564,1480000.0
1,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,0.0,156.0,79.0000,1035000.0
2,Abbotsford,3,h,SP,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,0.0,134.0,150.0000,1465000.0
3,Abbotsford,3,h,PI,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,1.0,94.0,160.2564,850000.0
4,Abbotsford,4,h,VB,Nelson,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,1.0,2.0,120.0,142.0000,1600000.0

**One-Hot Encoding**: is a technique used to convert categorical (text) data into numerical data so that machine learning algorithms can understand it.

In [21]:
# One-Hot Encoding:
df = pd.get_dummies(df, drop_first=True, dtype=int)
df.head()

,Rooms,Propertycount,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price,Suburb_Aberfeldie,...,CouncilArea_Moorabool Shire Council,CouncilArea_Moreland City Council,CouncilArea_Nillumbik Shire Council,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Whitehorse City Council,CouncilArea_Whittlesea City Council,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council
0,2,4019.0,2.5,2.0,1.0,1.0,202.0,160.2564,1480000.0,0,...,0,0,0,0,0,0,0,0,1,0
1,2,4019.0,2.5,2.0,1.0,0.0,156.0,79.0000,1035000.0,0,...,0,0,0,0,0,0,0,0,1,0
2,3,4019.0,2.5,3.0,2.0,0.0,134.0,150.0000,1465000.0,0,...,0,0,0,0,0,0,0,0,1,0
3,3,4019.0,2.5,3.0,2.0,1.0,94.0,160.2564,850000.0,0,...,0,0,0,0,0,0,0,0,1,0
4,4,4019.0,2.5,3.0,1.0,2.0,120.0,142.0000,1600000.0,0,...,0,0,0,0,0,0,0,0,1,0

In [24]:
# dividing dataframe into X (features) and y (target)
X = df.drop('Price', axis=1)
y = df['Price']

# splitting into training & testing data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=29)

In [40]:
# Linear Regression
LR_model = LinearRegression()
LR_model.fit(X_train, y_train)

LinearRegression()

In [41]:
# to check efficiency
print(f'Training efficiency score: {round(LR_model.score(X_train, y_train) * 100, 2)}')
print(f'Testing efficiency score: {round(LR_model.score(X_test, y_test) * 100, 2)}')
# Overfitting

Training efficiency score: 67.74
Testing efficiency score: 67.9

In [47]:
# prediction for Linear Regression
ypred = model.predict(X_test)
print(f'R2 score: {round(r2_score(y_test, ypred) * 100, 2)}')
print(f'MAE: {round(mean_absolute_error(y_test, ypred), 2)}')

R2 score: 67.9
MAE: 232748.92

**Ridge Regression - L2 Regularization**

In [48]:
# training ridge model
R_model = Ridge(alpha=5) # for huge difference between training & testing efficiencies, use alpha from
R_model.fit(X_train, y_train)

Ridge(alpha=5)

In [54]:
# prediction for Ridge Regression
ypred = R_model.predict(X_test)
print(f'Mean Absolute Regression: {round(mean_absolute_error(y_test, ypred), 2)}')

Mean Absolute Regression: 230569.49

In [55]:
# to check efficiency
print(f'Training efficiency score: {round(R_model.score(X_train, y_train) * 100, 2)}')
print(f'Testing efficiency score: {round(R_model.score(X_test, y_test) * 100, 2)}')
# Overfitting problem solved: efficiency of testing data got increased compared to Linear Regression

Training efficiency score: 67.46
Testing efficiency score: 68.17

**Lasso Regression - L1 Regularization**

In [56]:
# training lasso model
L_model = Lasso(alpha=50) # the alpha parameter controls the strength of regularization
L_model.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.680e+14, tolerance: 8.960e+11
  model = cd_fast.enet_coordinate_descent(

Lasso(alpha=50)

In [59]:
# prediction for Lasso Regression
ypred = L_model.predict(X_test)
print(f'Mean Absolute Regression: {round(mean_absolute_error(y_test, ypred), 2)}')

Mean Absolute Regression: 230538.48

In [60]:
# to check efficiency
print(f'Training efficiency score: {round(L_model.score(X_train, y_train) * 100, 2)}')
print(f'Testing efficiency score: {round(L_model.score(X_test, y_test) * 100, 2)}')
# Overfitting & Underfitting problem solved

Training efficiency score: 67.3
Testing efficiency score: 68.17