In [9]:
import pandas as pd

**Series**: Single Dimensional

In [10]:
pd.Series([10, 20, 30, 40])

0    10
1    20
2    30
3    40
dtype: int64

In [11]:
pd.Series([10, 20, 30, "Hi"])

0    10
1    20
2    30
3    Hi
dtype: object

In [12]:
pd.Series([10, 20, 30, (10, 20)])

0          10
1          20
2          30
3    (10, 20)
dtype: object

**DataFrame**

In [13]:
df = pd.DataFrame({'sname': ['A', 'B', 'C'], 'sid': [1, 2, 3], 'marks': [79, 86, 98]})
df

  sname  sid  marks
0     A    1     79
1     B    2     86
2     C    3     98

In [14]:
# edit values
df['sname'][0] = 'Rakshitha'
df['sname'][1] = 'Shreshta'
df['sname'][2] = 'Akriti'
df

/tmp/ipykernel_734/202363037.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['sname'][0] = 'Rakshitha'
/tmp/ipykernel_734/202363037.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sname'][0] = 'Rakshitha'
/tmp/ipykernel_734/202363037.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['sname'][1] = 'Shreshta'
/tmp/ipykernel_734/202363037.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sname'][1] = 'Shreshta'
/tmp/ipykernel_734/202363037.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['sname'][2] = 'Akriti'
/tmp/ipykernel_734/202363037.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sname'][2] = 'Akriti'

       sname  sid  marks
0  Rakshitha    1     79
1   Shreshta    2     86
2     Akriti    3     98

In [15]:
# add new column
df['bld_grp'] = ['O+', 'AB+', 'O+']
df

       sname  sid  marks bld_grp
0  Rakshitha    1     79      O+
1   Shreshta    2     86     AB+
2     Akriti    3     98      O+

**Methods & Variables in Pandas**

In [16]:
data = pd.read_csv("amazon_fires_.csv", encoding = 'ISO-8859-1') # encoding changes the Spanish in file to English for Colab to understand
data

       ano       mes     estado   numero  encontro
0     1998   Janeiro       Acre  0 Fires  1/1/1998
1     1999   Janeiro       Acre  0 Fires  1/1/1999
2     2000   Janeiro       Acre  0 Fires  1/1/2000
3     2001   Janeiro       Acre  0 Fires  1/1/2001
4     2002   Janeiro       Acre  0 Fires  1/1/2002
...    ...       ...        ...      ...       ...
6449  2012  Dezembro  Tocantins      128  1/1/2012
6450  2013  Dezembro  Tocantins       85  1/1/2013
6451  2014  Dezembro  Tocantins      223  1/1/2014
6452  2015  Dezembro  Tocantins      373  1/1/2015
6453  2016  Dezembro  Tocantins      119  1/1/2016

[6454 rows x 5 columns]

In [17]:
print("Column names:")
data.columns

Column names:

Index(['ano', 'mes', 'estado', 'numero', 'encontro'], dtype='object')

In [18]:
print("Number of rows, number of columns:")
data.shape

Number of rows, number of columns:

(6454, 5)

In [19]:
print("First 5 rows of the file:")
data.head()

First 5 rows of the file:

    ano      mes estado   numero  encontro
0  1998  Janeiro   Acre  0 Fires  1/1/1998
1  1999  Janeiro   Acre  0 Fires  1/1/1999
2  2000  Janeiro   Acre  0 Fires  1/1/2000
3  2001  Janeiro   Acre  0 Fires  1/1/2001
4  2002  Janeiro   Acre  0 Fires  1/1/2002

In [20]:
print("Last 5 rows of the file:")
data.tail()

Last 5 rows of the file:

       ano       mes     estado numero  encontro
6449  2012  Dezembro  Tocantins    128  1/1/2012
6450  2013  Dezembro  Tocantins     85  1/1/2013
6451  2014  Dezembro  Tocantins    223  1/1/2014
6452  2015  Dezembro  Tocantins    373  1/1/2015
6453  2016  Dezembro  Tocantins    119  1/1/2016

In [21]:
print("Information about the file:")
data.info()

Information about the file:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6454 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ano       6454 non-null   int64
 1   mes       6454 non-null   object
 2   estado    6454 non-null   object
 3   numero    6322 non-null   object
 4   encontro  6454 non-null   object
dtypes: int64(1), object(4)
memory usage: 252.2+ KB

In [22]:
# Considers only numeric columns
print("Statistical values:")
data.describe()

Statistical values:

               ano
count  6454.000000
mean   2007.461729
std       5.746654
min    1998.000000
25%    2002.000000
50%    2007.000000
75%    2012.000000
max    2017.000000

In [23]:
# To include object columns
data.describe(include='object')

            mes estado numero  encontro
count      6454   6454   6322      6454
unique       12     23   1728        20
top     Janeiro    Rio      0  1/1/1998
freq        541    717    433       324

In [24]:
print("Unique values from 'mes' column:")
data['mes'].unique()

Unique values from 'mes' column:

array(['Janeiro', 'Fevereiro', 'MarÃ§o', 'Abril', 'Maio', 'Junho',
       'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
      dtype=object)

In [25]:
print("Sorted values of 'mes' column:")
data['mes'].sort_values(ascending=True)

Sorted values of 'mes' column:

2452       Abril
3413       Abril
3414       Abril
3415       Abril
3416       Abril
          ...
5674    Setembro
5675    Setembro
5676    Setembro
5665    Setembro
885     Setembro
Name: mes, Length: 6454, dtype: object

**Boolean Filtering**

In [26]:
df = pd.read_csv('titanic.csv')
df.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [27]:
print("Filter only survived from survived column:")
df['survived'] == 1

Filter only survived from survived column:

0        True
1        True
2       False
3       False
4       False
        ...
1304    False
1305    False
1306    False
1307    False
1308    False
Name: survived, Length: 1309, dtype: bool

In [28]:
print("Survived and male:")
df[(df['survived'] == 1) & (df['sex'] == 'male')]

Survived and male:

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
5,1,"Anderson, Mr. Harry",male,48.0000,0,0,19952,26.5500,E12,S,1
14,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0000,0,0,27042,30.0000,A23,S,1
20,1,"Beckwith, Mr. Richard Leonard",male,37.0000,1,1,11751,52.5542,D35,S,1
22,1,"Behr, Mr. Karl Howell",male,26.0000,0,0,111369,30.0000,C148,C,1
...,...,...,...,...,...,...,...,...,...,...,...
1238,3,"Tenglin, Mr. Gunnar Isidor",male,25.0000,0,0,350033,7.7958,NaN,S,1
1240,3,"Thomas, Master. Assad Alexander",male,0.4167,0,1,2625,8.5167,NaN,C,1
1254,3,"Tornquist, Mr. William Henry",male,25.0000,0,0,LINE,0.0000,NaN,S,1
1256,3,"Touma, Master. Georges Youssef",male,7.0000,1,1,2650,15.2458,NaN,C,1
1277,3,"Vartanian, Mr. David",male,22.0000,0,0,2658,7.2250,NaN,C,1

In [29]:
print("Get female, survived who are in pclass = 3")
df[(df['sex'] == 'female') & (df['survived'] == 1) & (df['pclass'] == 3)]

Get female, survived who are in pclass = 3

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
603,3,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35.0,1,1,C.A. 2673,20.2500,NaN,S,1
604,3,"Abelseth, Miss. Karen Marie",female,16.0,0,0,348125,7.6500,NaN,S,1
607,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,0,2657,7.2292,NaN,C,1
612,3,"Aks, Mrs. Sam (Leah Rosen)",female,18.0,0,1,392091,9.3500,NaN,S,1
621,3,"Andersen-Jensen, Miss. Carla Christine Nielsine",female,19.0,1,0,350046,7.8542,NaN,S,1
...,...,...,...,...,...,...,...,...,...,...,...
1260,3,"Turja, Miss. Anna Sofia",female,18.0,0,0,4138,9.8417,NaN,S,1
1261,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S,1
1286,3,"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",female,38.0,0,0,2688,7.2292,NaN,C,1
1290,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,1
1300,3,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.0,1,0,2659,14.4542,NaN,C,1

In [30]:
print("Get passenges details who are either female or not survived")
df[(df['sex'] == 'female') | (df['survived'] == 0)]

Get passenges details who are either female or not survived

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0,0,0,24160,211.3375,B5,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.5500,C22 C26,S,0
6,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,1
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.8750,NaN,S,0

In [31]:
print("Get details of passengers embarked in either S or C")
df[(df['embarked'] == 'S') | (df['embarked'] == 'C')]

Get details of passengers embarked in either S or C

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

**DATA CLEANING**

In [32]:
data = pd.read_csv("amazon_fires_.csv", encoding = 'ISO-8859-1') # encoding changes the Spanish in file to English for Colab to understand
data

       ano       mes     estado   numero  encontro
0     1998   Janeiro       Acre  0 Fires  1/1/1998
1     1999   Janeiro       Acre  0 Fires  1/1/1999
2     2000   Janeiro       Acre  0 Fires  1/1/2000
3     2001   Janeiro       Acre  0 Fires  1/1/2001
4     2002   Janeiro       Acre  0 Fires  1/1/2002
...    ...       ...        ...      ...       ...
6449  2012  Dezembro  Tocantins      128  1/1/2012
6450  2013  Dezembro  Tocantins       85  1/1/2013
6451  2014  Dezembro  Tocantins      223  1/1/2014
6452  2015  Dezembro  Tocantins      373  1/1/2015
6453  2016  Dezembro  Tocantins      119  1/1/2016

[6454 rows x 5 columns]

In [33]:
# 2. Rearranging the columns
new_order = [2, 1, 0, 4, 3]
df[df.columns[new_order]]

,sex,name,pclass,sibsp,age
0,female,"Allen, Miss. Elisabeth Walton",1,0,29.0000
1,male,"Allison, Master. Hudson Trevor",1,1,0.9167
2,female,"Allison, Miss. Helen Loraine",1,1,2.0000
3,male,"Allison, Mr. Hudson Joshua Creighton",1,1,30.0000
4,female,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,1,25.0000
...,...,...,...,...,...
1304,female,"Zabour, Miss. Hileni",3,1,14.5000
1305,female,"Zabour, Miss. Thamine",3,1,NaN
1306,male,"Zakarian, Mr. Mapriededer",3,0,26.5000
1307,male,"Zakarian, Mr. Ortin",3,0,27.0000
1308,male,"Zimmerman, Mr. Leo",3,0,29.0000

In [34]:
# 1. Renaming the columns
data.rename(columns={
    'ano': 'year',
    'mes': 'month',
    'estado': 'state',
    'numero': 'no. of fires',
    'encontro': 'meeting date'
}, inplace=True)

data

      year     month      state no. of fires meeting date
0     1998   Janeiro       Acre      0 Fires     1/1/1998
1     1999   Janeiro       Acre      0 Fires     1/1/1999
2     2000   Janeiro       Acre      0 Fires     1/1/2000
3     2001   Janeiro       Acre      0 Fires     1/1/2001
4     2002   Janeiro       Acre      0 Fires     1/1/2002
...    ...       ...        ...          ...          ...
6449  2012  Dezembro  Tocantins          128     1/1/2012
6450  2013  Dezembro  Tocantins           85     1/1/2013
6451  2014  Dezembro  Tocantins          223     1/1/2014
6452  2015  Dezembro  Tocantins          373     1/1/2015
6453  2016  Dezembro  Tocantins          119     1/1/2016

[6454 rows x 5 columns]

In [35]:
# 3. Updating values inside the column
dict_var = {
    'Janeiro': 'January',
    'Fevereiro': 'February',
    'Março': 'March',
    'Abril': 'April',
    'Maio': 'May',
    'Junho': 'June',
    'Julho': 'July',
    'Agosto': 'August',
    'Setembro': 'September',
    'Outubro': 'October',
    'Novembro': 'November',
    'Dezembro': 'December'
}

data['month'] = data['month'].map(dict_var)

data

      year     month      state no. of fires meeting date
0     1998   January       Acre      0 Fires     1/1/1998
1     1999   January       Acre      0 Fires     1/1/1999
2     2000   January       Acre      0 Fires     1/1/2000
3     2001   January       Acre      0 Fires     1/1/2001
4     2002   January       Acre      0 Fires     1/1/2002
...    ...       ...        ...          ...          ...
6449  2012  December  Tocantins          128     1/1/2012
6450  2013  December  Tocantins           85     1/1/2013
6451  2014  December  Tocantins          223     1/1/2014
6452  2015  December  Tocantins          373     1/1/2015
6453  2016  December  Tocantins          119     1/1/2016

[6454 rows x 5 columns]

In [36]:
# 4. Removing unwanted data from the column
data['no. of fires'] = data['no. of fires'].str.strip(' Fires')
data

      year     month      state no. of fires meeting date
0     1998   January       Acre            0     1/1/1998
1     1999   January       Acre            0     1/1/1999
2     2000   January       Acre            0     1/1/2000
3     2001   January       Acre            0     1/1/2001
4     2002   January       Acre            0     1/1/2002
...    ...       ...        ...          ...          ...
6449  2012  December  Tocantins          128     1/1/2012
6450  2013  December  Tocantins           85     1/1/2013
6451  2014  December  Tocantins          223     1/1/2014
6452  2015  December  Tocantins          373     1/1/2015
6453  2016  December  Tocantins          119     1/1/2016

[6454 rows x 5 columns]

In [37]:
# 5. Changing the datatype of the column
data['no. of fires'] = data['no. of fires'].astype(float)
data

      year     month      state  no. of fires meeting date
0     1998   January       Acre           0.0     1/1/1998
1     1999   January       Acre           0.0     1/1/1999
2     2000   January       Acre           0.0     1/1/2000
3     2001   January       Acre           0.0     1/1/2001
4     2002   January       Acre           0.0     1/1/2002
...    ...       ...        ...           ...          ...
6449  2012  December  Tocantins         128.0     1/1/2012
6450  2013  December  Tocantins          85.0     1/1/2013
6451  2014  December  Tocantins         223.0     1/1/2014
6452  2015  December  Tocantins         373.0     1/1/2015
6453  2016  December  Tocantins         119.0     1/1/2016

[6454 rows x 5 columns]

In [38]:
# 6. Changing particular value in column
data['month'] = data['month'].str.replace('January', 'Jan')
data['month'] = data['month'].str.replace('December', 'Dec')
data

      year month      state  no. of fires meeting date
0     1998   Jan       Acre           0.0     1/1/1998
1     1999   Jan       Acre           0.0     1/1/1999
2     2000   Jan       Acre           0.0     1/1/2000
3     2001   Jan       Acre           0.0     1/1/2001
4     2002   Jan       Acre           0.0     1/1/2002
...    ...   ...        ...           ...          ...
6449  2012   Dec  Tocantins         128.0     1/1/2012
6450  2013   Dec  Tocantins          85.0     1/1/2013
6451  2014   Dec  Tocantins         223.0     1/1/2014
6452  2015   Dec  Tocantins         373.0     1/1/2015
6453  2016   Dec  Tocantins         119.0     1/1/2016

[6454 rows x 5 columns]

In [39]:
# 7. Applying in-built functions on column
data['state'] = data['state'].str.upper()
data.head(3)

   year month state  no. of fires meeting date
0  1998   Jan  ACRE           0.0     1/1/1998
1  1999   Jan  ACRE           0.0     1/1/1999
2  2000   Jan  ACRE           0.0     1/1/2000

In [40]:
# 8. Handling missing values
# i) dropping NaN values
# ii) replacing NaN values with 0 or avg
# iii) forward filling or back filling
# iv) dropping duplicates
data.dropna()
data.fillna(0)
data.fillna('ffill')
data.fillna('bfill')
data.drop_duplicates(inplace = True)
data

      year month      state  no. of fires meeting date
0     1998   Jan       ACRE           0.0     1/1/1998
1     1999   Jan       ACRE           0.0     1/1/1999
2     2000   Jan       ACRE           0.0     1/1/2000
3     2001   Jan       ACRE           0.0     1/1/2001
4     2002   Jan       ACRE           0.0     1/1/2002
...    ...   ...        ...           ...          ...
6449  2012   Dec  TOCANTINS         128.0     1/1/2012
6450  2013   Dec  TOCANTINS          85.0     1/1/2013
6451  2014   Dec  TOCANTINS         223.0     1/1/2014
6452  2015   Dec  TOCANTINS         373.0     1/1/2015
6453  2016   Dec  TOCANTINS         119.0     1/1/2016

[6424 rows x 5 columns]

In [41]:
dataframe = pd.DataFrame({'name':['Akriti', 'Shreshta', 'Rusku', 'Rusku'], 'age': [21, 21, 20, 20], 'bdy':[17, 18, 17, 17]})
print(dataframe)

       name  age  bdy
0    Akriti   21   17
1  Shreshta   21   18
2     Rusku   20   17
3     Rusku   20   17

In [42]:
# Remove duplicate rows
dataframe.drop_duplicates(inplace=True)

# Remove the 'bdy' column
dataframe.drop(['bdy'], axis=1, inplace=True)

print(dataframe)

       name  age
0    Akriti   21
1  Shreshta   21
2     Rusku   20

In [43]:
# 10. Removing unwanted rows
dataframe.drop(0, axis=0, inplace=True)

In [44]:
# 11. Resetting index
dataframe.reset_index() # resets the index and displays old index in 'index' column in the dataframe

   index      name  age
0      1  Shreshta   21
1      2     Rusku   20

In [45]:
# 12. Setting column name as index
dataframe.set_index('name')

          age
name
Shreshta   21
Rusku      20

**Aggregate functions (min, max, sum, mean, count) & groupby()**

In [46]:
# groupby(): used to group categorical columns

students = pd.DataFrame({
    'name': ['Akriti', 'Shreshta', 'Rusku', 'Shreya', 'Anora', 'Rashmi', 'Shraavya', 'Thrisha', 'Madhura'],
    'dept': ['CSBS', 'CSD', 'CSE', 'ISE', 'CSD', 'AIML', 'CSE', 'CSBS', 'AIML'],
    'usn': [5, 55, 45, 32, 50, 51, 52, 58, 29]
})

students.groupby('dept').size()

dept
AIML    2
CSBS    2
CSD     2
CSE     2
ISE     1
dtype: int64

In [47]:
hr = pd.read_csv('hr_data.csv')
hr.head(10)

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
5,1060,2,153,3,0,1,0,sales,low
6,1061,6,247,4,0,1,0,sales,low
7,1576,5,259,5,0,1,0,sales,low
8,1752,5,224,5,0,1,0,sales,low
9,1988,2,142,3,0,1,0,sales,low

In [48]:
# 1. Count employees per department
dept = hr.groupby('department')
dept['employee_id'].count()

department
IT             1227
RandD           787
accounting      767
hr              739
management      630
marketing       858
product_mng     902
sales          4140
support        2229
technical      2720
Name: employee_id, dtype: int64

In [49]:
# 2. Average monthly hours per department
hr.groupby('department')['average_montly_hours'].mean()

department
IT             202.215974
RandD          200.800508
accounting     201.162973
hr             198.684709
management     201.249206
marketing      199.385781
product_mng    199.965632
sales          200.911353
support        200.758188
technical      202.497426
Name: average_montly_hours, dtype: float64

In [50]:
# 3. Avergae of monthly hour based on salary
hr.groupby('salary')['average_montly_hours'].mean()

salary
high      199.867421
low       200.996583
medium    201.338349
Name: average_montly_hours, dtype: float64

In [51]:
# 4. Average time spent in company based on work accident
hr.groupby('Work_accident')['time_spend_company'].mean()

Work_accident
0    3.496960
1    3.505763
Name: time_spend_company, dtype: float64

In [52]:
# 5. Maximum hours spent per department
hr.groupby('department')['time_spend_company'].max()

department
IT             10
RandD           8
accounting     10
hr              8
management     10
marketing      10
product_mng    10
sales          10
support        10
technical      10
Name: time_spend_company, dtype: int64

**concat() & merge()**

In [53]:
# concatenating two dataframes
df1 = pd.DataFrame({'ename': ['A', 'B', 'C'], 'dept': ['CSBS', 'ECE', 'AIML']})
df2 = pd.DataFrame({'dept': ['AIML', 'CSD'], 'marks': [98, 96]})

In [54]:
pd.concat([df1, df2], ignore_index=True) # row-wise

  ename  dept  marks
0     A  CSBS    NaN
1     B   ECE    NaN
2     C  AIML    NaN
3   NaN  AIML   98.0
4   NaN   CSD   96.0

In [55]:
pd.concat([df1, df2], ignore_index=True, axis=1) # column-wise

   0     1     2     3
0  A  CSBS  AIML  98.0
1  B   ECE   CSD  96.0
2  C  AIML   NaN   NaN

In [56]:
# merging two dataframes
df1 = pd.DataFrame({'ename': ['A', 'B', 'C'], 'dept': ['CSBS', 'ECE', 'AIML']})
df2 = pd.DataFrame({'dept': ['AIML', 'CSD'], 'marks': [98, 96]})

# merge - same as inner join
pd.merge(df1, df2, on='dept')

  ename  dept  marks
0     C  AIML     98

In [57]:
# inner join
pd.merge(df1, df2, on='dept', how='inner')

  ename  dept  marks
0     C  AIML     98

In [58]:
# outer join
pd.merge(df1, df2, on='dept', how='outer')

  ename  dept  marks
0     C  AIML   98.0
1     A  CSBS    NaN
2   NaN   CSD   96.0
3     B   ECE    NaN

In [59]:
# left join
pd.merge(df1, df2, on='dept', how='left')

  ename  dept  marks
0     A  CSBS    NaN
1     B   ECE    NaN
2     C  AIML   98.0

In [60]:
# right join
pd.merge(df1, df2, on='dept', how='right')

  ename  dept  marks
0     C  AIML     98
1   NaN   CSD     96

**Pivot Table**

In [61]:
# Using titanic.csv

# 1. Average surviver by sex
df.pivot_table(values=['survived'], index = 'sex', aggfunc=['mean'])

            mean
        survived
sex
female  0.727468
male    0.190985

In [62]:
# 2. Count of passengers by class
df.pivot_table(values=['name'], index = 'pclass', aggfunc=['count'])

       count
        name
pclass
1        323
2        277
3        709

**map()**

In [63]:
marks = pd.DataFrame({'marks_scored':[10, 22, 33, 44]})
marks['double'] = marks['marks_scored'].map(lambda x: x*2)
marks

   marks_scored  double
0            10      20
1            22      44
2            33      66
3            44      88

**apply()**

In [64]:
subject = pd.DataFrame({'Math': [10, 20], 'Science': [50, 60]})
subject

   Math  Science
0    10       50
1    20       60

In [65]:
subject["Total"] = subject.apply(lambda row: row['Math'] + row['Science'], axis=1)
subject

   Math  Science  Total
0    10       50     60
1    20       60     80

**isnull()**

In [66]:
subject['Total'].isnull()

0    False
1    False
Name: Total, dtype: bool

In [67]:
subject['Total'].notnull()

0    True
1    True
Name: Total, dtype: bool